# Modified from https://github.com/Jorge-C/ordination/blob/master/.travis.yml
language: python
python:
  - "2.7"

# Setup anaconda
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  # Update conda itself
  - conda update --yes conda
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm

# Install packages
install:
  - conda create --yes -n env_name python=$TRAVIS_PYTHON_VERSION pip mkl numpy scipy scikit-learn pytest nose
  - source activate env_name
  - python setup.py install

# Run test
script:
  - pytest
